language: python

python:
  - 2.7
  - 3.3
  - 3.4

env:
  - DJANGO=1.5.12 MIGRATE='true'
  - DJANGO=1.6.11 MIGRATE='true'
  - DJANGO=1.7.11 MIGRATE='./manage.py migrate'
  - DJANGO=1.8.7 MIGRATE='./manage.py migrate'
  - DJANGO=1.9 MIGRATE='./manage.py migrate'

matrix:
  allow_failures:
    - env: DJANGO=1.9 MIGRATE='./manage.py migrate'
      python: 2.7
    - env: DJANGO=1.9 MIGRATE='./manage.py migrate'
      python: 3.3
    - env: DJANGO=1.9 MIGRATE='./manage.py migrate'
      python: 3.4

branches:
  only:
    - master

install:
  - pip install -r examples/requirements.txt
  - pip install Django==$DJANGO
  - python setup.py install

services:
  - redis-server

before_script:
  - pip freeze

script:
  - cd examples && $MIGRATE && ./manage.py test chatserver --settings=chatserver.tests.settings
